### ISSUE TITLE
option to set prefix to be used with `--split-conjecture`

### ISSUE THREAD

**Issue by c-cube** [tip-org/tools#10]
Currently, `tip --split-conjecture foo.smt2 dir/` will split the file `foo.smt2` into one result file per goal, but they will be named (for instance) `dir/0.smt2`,…,`dir/10.smt2`. It would be better to have `--split-conjecture --prefix foo` to obtain `dir/foo0.smt2`,…,`dir/foo10.smt2` in case `tip` is applied to several files each containing several goals.

**Comment by nick8325** [comment]
Perhaps the easiest would be just to make `--split-conjecture` not add a trailing slash? So then you could just say `tip --split-conjecture foo.smt2 dir/foo`. What do you think?

**Comment by c-cube** [comment]
Sounds like a good idea indeed.
