### ISSUE TITLE
issue with deriving "Enumerable" in tip-ghc/tip-spec

### ISSUE THREAD

**Issue by moajohansson** [tip-org/tools#15]
[FunPowBug.smt2.txt](https://github.com/tip-org/tools/files/716857/FunPowBug.smt2.txt)
Running tip-spec on the file attached (git won't let me attach a .smt2 file so it's a text file) produces an error:

A.hs:45:16: error:
    • Could not deduce (F.Enumerable a3) arising from a use of ‘funpow’
      from the context: (QC.Arbitrary a3, QC.CoArbitrary a3, P.Ord a3)
        bound by the type signature for:
                   rotate :: (QC.Arbitrary a3, QC.CoArbitrary a3, P.Ord a3) =>
                             Nat -> List a3 -> List a3
        at A.hs:(41,1)-(44,31)
      Possible fix:
        add (F.Enumerable a3) to the context of
          the type signature for:
            rotate :: (QC.Arbitrary a3, QC.CoArbitrary a3, P.Ord a3) =>
                      Nat -> List a3 -> List a3
    • In the expression: funpow x2 (\ z3 -> rotate1 z3) y3
      In an equation for ‘rotate’:
          rotate x2 y3 = funpow x2 (\ z3 -> rotate1 z3) y3

**Comment by nick8325** [comment]
Seems to work now?
