### ISSUE TITLE
tip-spec error in Translate.hs

### ISSUE THREAD

**Issue by mikkelmilo** [tip-org/tools#23]
Source files: [SetTest.zip](https://github.com/tip-org/tools/files/3515881/SetTest.zip)
I have converted the file attached file `SetTest.hs` to TIP using `tip-ghc SetTest.hs` which results in the attached file `SetTest.smt2`, but when I call `tip-spec -p --size 5 --test-size 14 SetTest.smt2` I get the following error 

`tip-spec: src/Tip/QuickSpec/Translate.hs, line 120: setmem_0
CallStack (from HasCallStack):
  error, called at src/Tip/QuickSpec/Translate.hs:120:73 in tip-spec-0.1-EMfSwidtKacBqLT3CVfDPS:Tip.QuickSpec.Translate`

Can you reproduce this error?
By the way, loving the tool so far. It's been super useful!

**Comment by mikkelmilo** [comment]
If I force `setmem` to be a function, and not a predicate, using the parameter `-f setmem` I don't get the error, by the way.

**Comment by nick8325** [comment]
Thanks for the bug report and the kind words! This was a bug in the version of QuickSpec which tip was using. Should be fixed now :)
