### ISSUE TITLE
Problems and workarounds for installing on an Ubuntu 18.04 Linux system

### ISSUE THREAD

**Issue by jafingerhut** [tip-org/tools#24]
Greetings, and thanks for creating this software and distributing it for free.

I tried installing this software on a newly installed Ubuntu 18.04 Linux system, and ran into some troubles that you may already know about, but I wanted to ask, anyway, in case I am going about this the wrong way.

First I followed these steps to install curl, git, and Haskell Stack, and clone a copy of this repository:
```
sudo apt-get install curl git
# Instructions from
# https://docs.haskellstack.org/en/stable/install_and_upgrade/#linux
curl -sSL https://get.haskellstack.org/ | sh
git clone https://github.com/tip-org/tools
cd tools
```
So far, everything is going well.  The version of Haskell stack installed is this:
```
$ stack --version
Version 2.1.3, Git revision 636e3a759d51127df2b62f90772def126cdf6d1f (7735 commits) x86_64 hpack-0.31.2
```
Then I try the next step in your README, but get an error message:
```
$ stack setup
Could not parse '/home/andy/tools/stack.yaml':
Aeson exception:
Error in $.packages[5]: failed to parse field 'packages': expected Text, encountered Object
See http://docs.haskellstack.org/en/stable/yaml_configuration/
```
I  do a bit of searching around and experimenting to find that if the stack.yaml file is changed according to the attached patch, then the `stack setup` command seems to succeed.

The `stack install` command gets about 95% of the way through, but then gets an error.  Again, through a bit of Google searching I find a suggestion to install another package first:
```
sudo apt-get install libtinfo-dev
```
and that did help the `stack install` command complete without any obvious errors.

Am I perhaps trying to use a version of stack that is not supported by this software?

In any case, thanks again, and if any of this would be useful to stick into an "Ubuntu 18.04 Linux install notes" section of the README, that may help others.

[tip-tools-stack.yaml-mod.patch.txt](https://github.com/tip-org/tools/files/3692964/tip-tools-stack.yaml-mod.patch.txt)

**Comment by nick8325** [comment]
Thanks for the patch! It seems that we were using a deprecated syntax that isn't supported in the newest version of Stack.

I've also added some hints on building to the README (see the section "Troubleshooting build errors").

**Comment by jafingerhut** [comment]
Great.  Thanks for the updates.
