### ISSUE TITLE
Doesn't compile with latest quickspec

### ISSUE THREAD

**Issue by aommm** [tip-org/tools#6]
tip-org/tools doesn't compile with [latest quickspec master](https://github.com/nick8325/quickspec/tree/b9ebfaea85c5f5f79edaf7ed32a18dc7c036bd27).

Also, for whom it may concern:
I've currently pinned quickspec to [this ancient commit](https://github.com/nick8325/quickspec/commit/de1eddcbcb8df5e7c12149fd97dd7201e4862c91) in order to get it to build. I also had to pin jukebox to 0.1.4 in order to build quickspec itself.

**Comment by moajohansson** [comment]
Should be fixed now. Use the stack-install option for tip-tools to get the correct version of QuickSpec 2.
